config/routes.rb
Rails.application.routes.draw do
  resources :platos do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  resources :ordenes do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  resources :comentarios do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end

  resources :restaurantes do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end

  
 
  devise_for :users
  resources :users, only: [:show] do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
	has_one_attached :avatar

end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  
  
  
  def index
    @restaurantes = Restaurante.all.order("created_at ASC")
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
    @restaurantes = Restaurante.find(params[:id])
  end

  # GET /restaurantes/new
  def new
    @restaurantes = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
    @restaurante = Restaurante.find(params[:id])
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    puts('1234556778888a88as8888')
    puts(restaurante_params)
    puts(params[:restaurante])
    puts('1234556778888a88as8888')
    @restaurantes = Restaurante.new(params[:restaurante].permit(:titulo, :correo, :direccion, :valoracion, :telefono, :url, :avatar))
    if @restaurantes.save
       redirect_to :action => "index"
    end
  end

  def update
    puts('---------------------------')
    respond_to do |format|
      if @restaurantes.update(restaurante_params)
        puts('======================================')
        format.html { redirect_to :action=> "index", notice: 'Restaurante was successfully updated.' }
        format.json { render :index, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  

 
  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json


  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurantes.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurantes = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.fetch(:restaurante, {})
    end

  private
    def restaurante_params
      params.require(:restaurante).permit(:titulo, :correo, :direccion, :valoracion, :telefono, :url, :avatar)
    end
  end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_form.html.erb
<%= form_with(model: restaurante, local: true) do |form| %>
  <% if restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% restaurante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurantes/create.html.erb
<h1>New Restaurante</h1>

<%= form_with(model: Restaurante.new, local: true) do |form| %>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 200%;">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 200%;">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 200%;">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 200%;">
    <%= form.label :valoracion %>
    <%= form.text_field :valoracion %>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 200%;">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 200%;">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<style> 
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style> 

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  
  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>

app/views/restaurantes/edit.html.erb
<h1 style="color:white;font-family: ubuntu;font-size: 300%;">Editar Restaurante</h1>


<%= form_with(model: @restaurante, url: restaurante_path(@restaurantes)) do |form| %>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 130%;">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 130%;">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 130%;">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 130%;">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>


  <div class="field" style="color:white;font-family: ubuntu;font-size: 130%;">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 130%;">
    <%= form.label :avatar%>
    <%= form.file_field :avatar%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<style>
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>

app/views/restaurantes/index.html.erb
 <p id="notice"><%= notice %></p>
<h1 style="color:white;font-family: ubuntu;font-size: 400%;margin-top:0px">Restaurantes</h1>



<div class="row">
<% n = 1 %>
<% @restaurantes.each do |restaurante| %>

<!--<h5 style="color:white;font-family: ubuntu;font-size: 200%;margin-left:20px;margin-top:30px"><%= n %>. <%= restaurante.titulo %></h5>
-->
  <% if restaurante.avatar.attached? %>
<div class="p-3">
<a href="/restaurantes/ <%= n %>">


        <div class="product-div2">
          <img src="<%=(url_for(restaurante.avatar))%>" class="resto_foto">
            <div class="text-view transition">
                <h4><%= restaurante.titulo %></h4>
            </div></div>

</a>
</div>
  <% else %>
  <%= image_tag("no_image.jpg") %>
  <%= link_to 'Ver Restaurante', restaurante_path(restaurante),:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px' %>
  <% end %>

<!--  <%= link_to 'Ver restaurante', restaurante, method: :delete, data: { confirm: 'Estas seguro?' }%>
-->
  <% n += 1 %>

<% end %>
</div>



<style>
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>

</nav>
</main>




<footer class="fixed-bottom">

  <div class="footer-copyright text-center py-0">
    <%= link_to 'Nuevo restaurante', new_restaurante_path ,:style=>'color: white;font-family: ubuntu;font-size: 140%;background-color: red'%>
    </div>
    <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
     </div>
  </footer>

app/views/restaurantes/new.html.erb
<h1 style="color:white;font-family: ubuntu;font-size: 400%;">Nuevo Restaurante</h1>

<%= form_with(model: Restaurante.new, local: true) do |form| %>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
    <%= form.label :titulo%>
    <%= form.text_field :titulo%>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
    <%= form.label :correo%>
    <%= form.text_field :correo%>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
    <%= form.label :direccion%>
    <%= form.text_field :direccion%>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
    <%= form.label :valoracion%>
    <%= form.text_field :valoracion%>
  </div>

  <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
    <%= form.label :telefono%>
    <%= form.text_field :telefono%>
  </div>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
    <%= form.label :url%>
    <%= form.text_field :url%>
  </div>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
    <%= form.label :avatar%>
    <%= form.file_field :avatar%>
  </div>

  <div class="actions">
    <%= form.submit :Submit%>
  </div>
<% end %>


<style> 
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style> 

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  
  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>

app/views/restaurantes/show.html.erb
<style>
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>





<p id="notice"><%= notice %></p>

<h3 style="color:white;font-family: ubuntu;font-size: 400%;margin-top:20px"> <%= @restaurantes.titulo %> </h3>


<div class="mt-10">
<div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
  <div class="btn-group mr-2" role="group" aria-label="First group">
    <button type="button" style="background-color:red" class="btn btn-secondary"><%= link_to 'Ver Platos', platos_path ,:style=>'color: white;font-family: ubuntu;font-size: 100%' %>
</button>
    <button type="button" style="background-color:red" class="btn btn-secondary"><%= link_to 'Crear Plato', new_plato_path ,:style=>'color: white;font-family: ubuntu;font-size: 100%' %>
</button>
    <button type="button" style="background-color:red" class="btn btn-secondary"><%= link_to 'Ver Ordenes', ordene_path(@restaurantes) ,:style=>'color: white;font-family: ubuntu;font-size: 100%' %>
</button>
    <button type="button" style="background-color:red" class="btn btn-secondary"><%= link_to 'Ver Comentarios', comentarios_path ,:style=>'color: white;font-family: ubuntu;font-size: 100%' %>
</button>
    <button type="button" style="background-color:red" class="btn btn-secondary"><%= link_to 'Crear Comentario', new_comentario_path  ,:style=>'color: white;font-family: ubuntu;font-size: 100%'%>
</button>
    <button type="button" style="background-color:red" class="btn btn-secondary"><%= link_to 'Crear Orden', new_ordene_path  ,:style=>'color: white;font-family: ubuntu;font-size: 100%'%>
</button>
    <button type="button" style="background-color:red" class="btn btn-secondary"><%= link_to 'Editar Restaurante', edit_restaurante_path  ,:style=>'color: white;font-family: ubuntu;font-size: 100%'%>
</button>


  </div>
  <div class="btn-group" role="group" aria-label="Third group">
    <button type="button" style="background-color:red" class="btn btn-secondary">  <%= link_to 'Back', restaurantes_path  ,:style=>'color: white;font-family: ubuntu;font-size: 100%'%>
</button>
  </div>
</div>
</div>
<div class="row p-4">
  <div class="col-md-4">
<% if @restaurantes.avatar.attached? %>
    <img src="<%=(url_for(@restaurantes.avatar))%>" class="resto-show">
<% else %>
  <%= image_tag("no_image.jpg") %>
<% end %>
</div>

<div class="col-md-8">
<p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Nombre: <%= @restaurantes.titulo %></p>
<p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Direccion: <%= @restaurantes.direccion %></p>
<p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Telefono: <%= @restaurantes.telefono %></p>
<p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Valoracion: <%= @restaurantes.valoracion %></p>
<p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Correo: <%= @restaurantes.correo %></p>
<p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Url: <%= @restaurantes.url %></p>
</div>
</div>





<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>

<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>