config/routes.rb
Rails.application.routes.draw do
  resources :platos do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  resources :ordenes do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  resources :comentarios do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end

  resources :restaurantes do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end

  
 
  devise_for :users
  resources :users, only: [:show] do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plato.rb
class Plato < ApplicationRecord
    has_one_attached :imagen

end

app/controllers/platos_controller.rb
class PlatosController < ApplicationController
 
  before_action :set_plato, only: [:show, :edit, :update, :destroy]
  # GET /platos
  # GET /platos.json
  def index
    @platos = Plato.all.order("created_at ASC")
  end

  # GET /platos/1
  # GET /platos/1.json

  def show
    @platos = Plato.where(:id => params[:id])
    if @platos.present?
      puts ("plato")
      puts (@platos)
    else
      puts("NO HAY PLATOS")
    end
  end

  # GET /platos/new
  def new
    @platos = Plato.new
  end

  # GET /platos/1/edit
  def edit
    @plato = Plato.find(params[:id])
  end

  # POST /platos
  # POST /platos.json
  def create
    @plato = Plato.new(plato_params)

    respond_to do |format|
      if @plato.save
        format.html { redirect_to restaurante_platos_path(@plato), notice: 'Plato was successfully created.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @plato.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    puts('---------------------------')
    respond_to do |format|
      puts('------------------###--------')

      if @platos.update(plato_params)
        puts('--------###--------###--------')

        format.html { redirect_to :action=> "index", notice: 'Plato was successfully updated.' }
        format.json { render :index, status: :ok, location: @plato }
      else
        format.html { render :edit }
        format.json { render json: @plato.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /platos/1
  # DELETE /platos/1.json
  def destroy
    @platos.destroy
    respond_to do |format|
      format.html { redirect_to platos_url, notice: 'Plato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plato
      @platos = Plato.find(params[:id])
    end



    def plato_params
      params.fetch( :plato, {})
    end



  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def plato_params
      params.require(:plato).permit(:nombre, :precio, :descripcion, :cantidad_de_personas_sugeridas, :valoracion)
    end
  end

app/helpers/platos_helper.rb
module PlatosHelper
end

app/views/platos/_form.html.erb
<%= form_with(model: plato, local: true) do |form| %>
  <% if plato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plato.errors.count, "error") %> prohibited this plato from being saved:</h2>

      <ul>
      <% plato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :cantidad_de_personas_sugeridas %>
    <%= form.number_field :cantidad_de_personas_sugeridas %>
  </div>

  <div class="field">
    <%= form.label :valoracion %>
    <%= form.number_field :valoracion %>
  </div>
  <div class="field">
    <%= form.label :imagen%>
    <%= form.file_field :imagen%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/platos/edit.html.erb
<h1 style="color:white;font-family: ubuntu;font-size: 400%;">Editar Plato</h1>


<%= form_with(model: @plato, url: plato_path(@plato), method: 'patch') do |form| %>
  <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
    <%= form.label :nombre %>
    <%= form.text_field :nombre%>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<style> 
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style> 

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  
  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>

app/views/platos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="color:white;font-family: ubuntu;font-size: 400%;margin-top:20px">Platos</h1>

<table>
  <thead>
    <tr>
    <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Id</th>

    <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Nombre</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Precio</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Descripcion</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Cantidad de personas sugeridas</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">Valoracion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @platos.each do |plato| %>
      <tr>
      <td  style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px"><%= plato.id %></td>

      <td  style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px"><%= plato.nombre %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px"><%= plato.precio %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px"><%= plato.descripcion %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px"><%= plato.cantidad_de_personas_sugeridas %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px"><%= plato.valoracion %></td>
        <td ><%= link_to 'Ver plato', plato, :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'  %></td>

        <% if current_user.try(:admin?) %>
          <td><%= link_to 'Editar', edit_plato_path(plato) %></td>
          <td><%= link_to 'Eliminar plato', plato, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.try(:admin?) %>
  <%= link_to 'Nuevo Plato', new_plato_path %>
<% end %>

<style> 
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style> 

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  
  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>

app/views/platos/new.html.erb
<h1 style="color:white;font-family: ubuntu;font-size: 400%;">Nuevo Plato</h1>

<%= form_with(model: Plato.new, local: true) do |form| %>

<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :nombre %>
<%= form.text_field :nombre %>
</div>

<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :precio %>
<%= form.text_field :precio %>
</div>

<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :descripcion %>
<%= form.text_area :descripcion %>
</div>

<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :cantidad_de_personas_sugeridas %>
<%= form.number_field :cantidad_de_personas_sugeridas %>
</div>

<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :valoracion %>
<%= form.number_field :valoracion %>
</div>
<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :imagen%>
<%= form.file_field :imagen%>
</div>

<div class="actions">
<%= form.submit %>
</div>
<% end %>

<style> 
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style> 

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  
  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>

app/views/platos/show.html.erb
<h1 style="color:white;font-family: ubuntu;font-size: 400%;">Información</h1>

<p id="notice"><%= notice %></p>
<% if @platos %>
  <% @platos.each do |plato|%>
    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px"> 
      <strong>Nombre:</strong>
      <%= plato.nombre %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Precio:</strong>
      <%= plato.precio %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Descripcion:</strong>
      <%= plato.descripcion %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Cantidad de personas sugeridas:</strong>
      <%= plato.cantidad_de_personas_sugeridas %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Valoracion:</strong>
      <%= plato.valoracion %>
    </p>
    <% if plato.imagen.attached? %>
      <img src="<%=(url_for(plato.imagen))%>">
    <% else %>
      <%= image_tag("no_image.jpg") %>
    <% end %>   
    <%= link_to 'Editar', edit_plato_path(plato), :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px' %>
  <% end %>
 
<% end %>
<% if @platos==[] %>
  <p > No existen platos </p>
<% end %>

<%= link_to 'Atrás', restaurantes_path ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px' %>

<style> 
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style> 

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  
  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>