grupo13/config/routes.rb
Rails.application.routes.draw do
  resources :platos
  resources :ordenes
  resources :comentarios
  resources :restaurantes
  get '/restaurantes', to: 'restaurantes#index'
  post '/restaurantes/new', to: 'restaurantes#create' 
  get '/restaurantes/new', to: 'restaurante/#index'
  get '/restaurantes/:id', to: 'restaurantes#show'
  get '/restaurantes/:id', to: 'restaurantes#edit'
  post '/comentarios/new', to: 'comentarios#create'
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

grupo13/app/models/restaurante.rb
class Restaurante < ApplicationRecord
end

grupo13/app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
    puts 'DALE CARAJO'
    @restaurantes = Restaurante.find(params[:id])
  end

  # GET /restaurantes/new
  def new
    @restaurantes = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
    @restaurantes = Restaurante.find(params[:id])
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    puts('1234556778888a88as8888')
    puts(restaurante_params)
    puts(params[:restaurante])
    puts('1234556778888a88as8888')
    @restaurantes = Restaurante.new(params[:restaurante].permit(:titulo, :correo, :direccion, :valoracion, :telefono, :url))
    if @restaurantes.save
       redirect_to :action => "index"
    end
  end

  private
    def restaurante_params
      params.require(:restaurante).permit(:titulo, :correo, :direccion, :valoracion, :telefono, :url)
    end

 
  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurantes.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurantes.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurantes = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.fetch(:restaurante, {})
    end

end

grupo13/app/views/restaurantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurantes</h1>

<% n = 1 %>
<% @restaurantes.each do |restaurante| %>
  <h5><%= n %>. <%= restaurante.titulo %></h5>
  <%= link_to 'Ver restaurante', restaurante_path(restaurante) %>
  <% n += 1 %>
<% end %>
<b>

<%= link_to 'Nuevo restaurante', new_restaurante_path %>

grupo13/app/views/restaurantes/new.html.erb
<h1>New Restaurante</h1>

<%= form_with(model: Restaurante.new, local: true) do |form| %>
  <div class="field">
    <%= form.label :titulo%>
    <%= form.text_field :titulo%>
  </div>

  <div class="field">
    <%= form.label :correo%>
    <%= form.text_field :correo%>
  </div>

  <div class="field">
    <%= form.label :direccion%>
    <%= form.text_field :direccion%>
  </div>

  <div class="field">
    <%= form.label :valoracion%>
    <%= form.text_field :valoracion%>
  </div>

  <div class="field">
    <%= form.label :telefono%>
    <%= form.text_field :telefono%>
  </div>
  <div class="field">
    <%= form.label :url%>
    <%= form.text_field :url%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

grupo13/app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<h3> Informacion </h3>
<p>Nombre: <%= @restaurantes.titulo %></p>
<p>Direccion: <%= @restaurantes.direccion %></p>
<p>Telefono: <%= @restaurantes.telefono %></p>
<p>Valoracion: <%= @restaurantes.valoracion %></p>
<p>Correo: <%= @restaurantes.correo %></p>
<p>Url: <%= @restaurantes.url %></p>

<%= link_to 'Ver Platos', platos_path %>
<b>
<%= link_to 'Ver Ordenes', ordenes_path %>
<b>
<%= link_to 'Ver Comentarios', comentarios_path %>
<b>
<%= link_to 'Back', restaurantes_path %>
<b>
<%= link_to 'Crear Orden', new_ordene_path %>