config/routes.rb
Rails.application.routes.draw do
  resources :platos do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  resources :ordenes do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  resources :comentarios do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end

  resources :restaurantes do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end

  
 
  devise_for :users
  resources :users, only: [:show] do
    resources :platos
    resources :ordenes
    resources :comentarios
    resources :restaurantes
  end
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ordene.rb
class Ordene < ApplicationRecord
end

app/controllers/ordenes_controller.rb
class OrdenesController < ApplicationController

  before_action :authenticate_user!, :except => [:show, :index]

  # GET /ordenes
  # GET /ordenes.json
  def index
    @ordenes = Ordene.all
  end

  # GET /ordenes/1
  # GET /ordenes/1.json
  def show
    @ordenes = Ordene.where(:id => params[:id])
    if @ordenes.exists?
      puts("HAY ORDEN")
    else
      puts("No hay ordenes")
    end
  end

  # GET /ordenes/new
  def new
    @ordene = Ordene.new
  end

  # GET /ordenes/1/edit
  def edit
  end

  # POST /ordenes
  # POST /ordenes.json
  def create
    @ordene = Ordene.new(ordene_params)

    respond_to do |format|

    #  if @ordene.aceptar

        if @ordene.save
          format.html { redirect_to @ordene, notice: 'Ordene was successfully created.' }
	  format.json { render :show, status: :created, location: @ordene }
        else
	  format.html { render :new }
          format.json { render json: @ordene.errors, status: :unprocessable_entity }
	      end
      end
    #end
  end

  # PATCH/PUT /ordenes/1
  # PATCH/PUT /ordenes/1.json
  def update
    respond_to do |format|
      if @ordene.update(ordene_params)
        format.html { redirect_to @ordene, notice: 'Ordene was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordene }
      else
        format.html { render :edit }
        format.json { render json: @ordene.errors, status: :unprocessable_entity }
      end
    end
  end
  def standby
    @ordene = Ordene.new(ordene_params)
    if array
      array << @ordene
    else
      array = []
      array << @ordene
    end
    redirect_to '../views/ordenes/standby.html.erb'
  end

  # DELETE /ordenes/1
  # DELETE /ordenes/1.json
  def destroy
    @ordene.destroy
    respond_to do |format|
      format.html { redirect_to ordenes_url, notice: 'Ordene was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordene
      @ordene = Ordene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordene_params
      params.require(:ordene).permit(:platos_pedidos_en_la_orden, :precio_final_a_pagar, :medio_de_pago, :direccion_de_envio, :hora_estimada_de_entrega, :estado_del_pedido, :notas)
    end
end

app/helpers/ordenes_helper.rb
module OrdenesHelper
end

app/views/ordenes/_form.html.erb
<%= form_with(model: ordene, local: true) do |form| %>
  <% if ordene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordene.errors.count, "error") %> prohibited this ordene from being saved:</h2>

      <ul>
      <% ordene.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :platos_pedidos_en_la_orden %>
    <%= form.text_field :platos_pedidos_en_la_orden %>
  </div>

  <div class="field">
    <%= form.label :precio_final_a_pagar %>
    <%= form.text_field :precio_final_a_pagar %>
  </div>

  <div class="field">
    <%= form.label :medio_de_pago %>
    <%= form.text_field :medio_de_pago %>
  </div>

  <div class="field">
    <%= form.label :direccion_de_envio %>
    <%= form.text_field :direccion_de_envio %>
  </div>

  <div class="field">
    <%= form.label :hora_estimada_de_entrega %>
    <%= form.time_select :hora_estimada_de_entrega %>
  </div>

  <div class="field">
    <%= form.label :estado_del_pedido %>
    <%= form.text_field :estado_del_pedido %>
  </div>

  <div class="field">
    <%= form.label :notas %>
    <%= form.text_area :notas %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ordenes/edit.html.erb
<h1 style="color:white;font-family: ubuntu;font-size: 400%;">Nuevs Orden</h1>

<%= form_with(model: Ordene.new, local: true) do |form| %>
    <% if ordene.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(ordene.errors.count, "error") %> prohibited this ordene from being saved:</h2>
  
        <ul>
        <% ordene.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  

    <div class="field"  style="color:white;font-family: ubuntu;font-size: 150%;">
    <%= form.label :platos_pedidos_en_la_orden %>
    <%= form.text_field :platos_pedidos_en_la_orden %>
    </div>
  
    <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
      <%= form.label :medio_de_pago %>
      <%= form.text_field :medio_de_pago %>
    </div>
  
    <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
      <%= form.label :direccion_de_envio %>
      <%= form.text_field :direccion_de_envio %>
    </div>
  
    <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
      <%= form.label :hora_estimada_de_entrega %>
      <%= form.time_select :hora_estimada_de_entrega %>
    </div>
  
    <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
      <%= form.label :estado_del_pedido %>
      <%= form.text_field :estado_del_pedido %>
    </div>
  
    <div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
      <%= form.label :notas %>
      <%= form.text_area :notas %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  <style> 
  body { background-image: url('/assets/nacha.png') !important;
      background-position: collapse !important;
      background-repeat: no-repeat !important;
      background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
  </style> 
  
  <main class="container" role="main">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  
  
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
  
    <ul class="navbar-nav mr-auto">
    <% if signed_in? %>
  
    <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


    <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  
    
    <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
    <% else %>
    <li class="nav-item active">
    <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
  </li>
  
  <li class="nav-item active">
    <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
  </li>
  <% end %>
  
        </div>
      </li>
    </ul>
  
  </div>
  </nav>
  </main>
  
  
  
  
  <footer class="fixed-bottom">
    <div class="footer-copyright text-center py-3">
       <font color="white">Desarrollado por Trejos Dream Team</font>
    </div>
    </footer>

app/views/ordenes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordenes</h1>

<table>
  <thead>
    <tr>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px">Platos pedidos en la orden</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px">Precio final a pagar</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px">Medio de pago</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px">Direccion de envio</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px">Hora estimada de entrega</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px">Estado del pedido</th>
      <th style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px">Notas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordenes.each do |ordene| %>
      <tr>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px"><%= ordene.platos_pedidos_en_la_orden %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px"><%= ordene.precio_final_a_pagar %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px"><%= ordene.medio_de_pago %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px"><%= ordene.direccion_de_envio %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px"><%= ordene.hora_estimada_de_entrega %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px"><%= ordene.estado_del_pedido %></td>
        <td style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px;margin-left:20px"><%= ordene.notas %></td>
        <td style="color:white;font-family: ubuntu;font-size: 100%;margin-top:20px;margin-left:20px"><%= link_to 'Mostrar', ordene %></td>
        <td style="color:white;font-family: ubuntu;font-size: 100%;margin-top:20px;margin-left:20px"><%= link_to 'Editar', edit_ordene_path(ordene) %></td>
        <td style="color:white;font-family: ubuntu;font-size: 100%;margin-top:20px;margin-left:20px"><%= link_to 'Eliminar', ordene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Volver a Restaurantes', restaurantes_path , :style=>"color:white;font-family: ubuntu;font-size: 100%;margin-top:20px"%>

<%= link_to 'Crear Orden', new_ordene_path, :style=>"color:white;font-family: ubuntu;font-size: 100%;margin-top:20px;margin-left:20px"%>

<style> 
  body { background-image: url('/assets/nacha.png') !important;
      background-position: collapse !important;
      background-repeat: no-repeat !important;
      background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
  </style> 
  
  <main class="container" role="main">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  
  
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
  
    <ul class="navbar-nav mr-auto">
    <% if signed_in? %>
  
    <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


    <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  
    
    <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
    <% else %>
    <li class="nav-item active">
    <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
  </li>
  
  <li class="nav-item active">
    <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
  </li>
  <% end %>
  
        </div>
      </li>
    </ul>
  
  </div>
  </nav>
  </main>
  
  
  
  
  <footer class="fixed-bottom">
    <div class="footer-copyright text-center py-3">
       <font color="white">Desarrollado por Trejos Dream Team</font>
    </div>
    </footer>

app/views/ordenes/new.html.erb
<h1 style="color:white;font-family: ubuntu;font-size: 400%;">Nueva Orden</h1>

<%= form_with(model: Ordene.new, local: true) do |form| %>

<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :pedido %>
<%= form.text_field :pedido %>
</div>

<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :precio_total %>
<%= form.text_field :precio_total %>
</div>

<div class="field" style="color:white;font-family: ubuntu;font-size: 150%;">
<%= form.label :detalles %>
<%= form.text_area :detalles %>
</div>

<div class="actions">
<%= form.submit %>
</div>
<% end %>

<style>
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>

app/views/ordenes/show.html.erb
<h1 style="color:white;font-family: ubuntu;font-size: 400%;">Órdenes</h1>


<p id="notice"><%= notice %></p>
<% if @ordenes %>
  <% @ordenes.each do |ordene| %>
    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Platos pedidos en la orden:</strong>
      <%= ordene.platos_pedidos_en_la_orden %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Precio final a pagar:</strong>
      <%= ordene.precio_final_a_pagar %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Medio de pago:</strong>
      <%= ordene.medio_de_pago %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Direccion de envio:</strong>
      <%= ordene.direccion_de_envio %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Hora estimada de entrega:</strong>
      <%= ordene.hora_estimada_de_entrega %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Estado del pedido:</strong>
      <%= ordene.estado_del_pedido %>
    </p>

    <p style="color:white;font-family: ubuntu;font-size: 150%;margin-top:20px">
      <strong>Notas:</strong>
      <%= ordene.notas %>
    </p>
  <% end %>
  <% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_ordene_path(ordene) %>
  <% end %>
<% end %>
<% if @ordenes==[] %>
  <p>No existen ordenes actualmente</p>
<% end %>

<%= link_to 'Back', restaurantes_path %>
<style> 
body { background-image: url('/assets/nacha.png') !important;
    background-position: collapse !important;
    background-repeat: no-repeat !important;
    background-size: cover !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style> 

<main class="container" role="main">
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">


<div class="collapse navbar-collapse" id="navbarsExampleDefault">

  <ul class="navbar-nav mr-auto">
  <% if signed_in? %>

  <%=link_to "Perfil", current_user,class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>


  <%=link_to "Mostrar Restaurantes", restaurantes_url, class: "nav-link", :style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>

  
  <%= link_to "Salir", destroy_user_session_path, method: :delete ,class: "nav-link" ,:style=>'color: white;font-family: ubuntu;font-size: 100%;margin-left:20px'%>
  
  <% else %>
  <li class="nav-item active">
  <a class="nav-link" href="users/sign_in">Ingresar <span class="sr-only">(current)</span></a>
</li>

<li class="nav-item active">
  <a class="nav-link" href="users/sign_up">Registrarse <span class="sr-only">(current)</span></a>
</li>
<% end %>

      </div>
    </li>
  </ul>

</div>
</nav>
</main>




<footer class="fixed-bottom">
  <div class="footer-copyright text-center py-3">
     <font color="white">Desarrollado por Trejos Dream Team</font>
  </div>
  </footer>

app/views/ordenes/standby.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordenes</h1>

<table>
  <thead>
    <tr>
      <th>Platos pedidos en la orden</th>
      <th>Precio final a pagar</th>
      <th>Medio de pago</th>
      <th>Direccion de envio</th>
      <th>Hora estimada de entrega</th>
      <th>Estado del pedido</th>
      <th>Notas</th>
      <th>Aceptar o Rechazar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% array.each do |orden| %>
      <tr>
        <td><%= ordene.platos_pedidos_en_la_orden %></td>
        <td><%= ordene.precio_final_a_pagar %></td>
        <td><%= ordene.medio_de_pago %></td>
        <td><%= ordene.direccion_de_envio %></td>
        <td><%= ordene.hora_estimada_de_entrega %></td>
        <td><%= ordene.estado_del_pedido %></td>
        <td><%= ordene.notas %></td>
        <%= check_box_tag(:aceptar) %>
	      <%= label_tag(:aceptar, "Aceptar") %>
	      <%= check_box_tag(:rechazar) %>
	      <%= label_tag(:rechazar, "Rechazar") %>
        <td><%= form.submit :Registrar lo pedido%></td>
        <td><%= link_to 'Show', ordene %></td>
        <td><%= link_to 'Edit', edit_ordene_path(ordene) %></td>
        <td><%= link_to 'Destroy', ordene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Volver a Restaurantes', restaurantes_path %>

<%= link_to 'Crear Orden', new_ordene_path %>